### ISSUE TITLE
Add travis CI file

### ISSUE THREAD

**Issue by guilhermehas** [ed-2018-T2/projeto#11]
In this issue, we need to integrated our tests with travis CI or circle CI. Some continuous integration service.

**Comment by odanoburu** [comment]
pra #10 e essa issue vcs podem transformar isso num pacote de verdade; `raco pkg new reproduce-oab` deve criar um novo diretório com o esqueleto pronto, incluindo onde vão os testes e um `.travis.yml`

**Comment by guilhermehas** [comment]
Não consegui colocar o coveralls pra funcionar no projeto
